apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-hooks-http
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: image-hooks-http
  template:
    metadata:
     labels:
       app.kubernetes.io/name: image-hooks-http
    spec:
      containers:
        - name: image-hooks-http
          image: bigkevmcd/image-hooks:latest
          imagePullPolicy: Always
          args: ["http", "--parser", "docker"]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/image-hooks
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: image-hooks-secret
                  key: token
      volumes:
        - name: config-volume
          configMap:
            name: image-hooks-config
---
apiVersion: v1
kind: Service
metadata:
  name: image-hooks-http
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: image-hooks-http
  ports:
    - protocol: TCP
      port: 8080
